service: farmacia-API # NOTE: update this with your service name

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  profile:  ${file(./config/config.${self:provider.stage}.js):awsProfile}
  # apiGateway:
  #   restApiId: ${file(./config/config.${self:provider.stage}.js):restApiId}
  #   restApiRootResourceId: ${file(./config/config.${self:provider.stage}.js):restApiRootResourceId}
  environment:
    database: ${file(./config/config.${self:provider.stage}.js):database}

functions:
  getProducts:
    handler: handler.getProducts
     - http:
         path: products/get
         method: get
         timeout: 30
         private: true       

plugins:
  - serverless-offline